// <auto-generated />
using System;
using Cooperativa.App.Domain.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Cooperativa.App.Migrations
{
    [DbContext(typeof(CooperativaDbContext))]
    [Migration("20241004204141_tipoPrestamo")]
    partial class tipoPrestamo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Cooperativa.App.Domain.Model.Caja.Caja", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("EgresoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<Guid?>("IngresoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsSoftDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Moneda_Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Referencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ResponsableId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("SaldoActual")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal>("SaldoAnterior")
                        .HasColumnType("decimal(9,2)");

                    b.HasKey("Id");

                    b.HasIndex("EgresoId");

                    b.HasIndex("IngresoId");

                    b.ToTable("Caja");
                });

            modelBuilder.Entity("Cooperativa.App.Domain.Model.Caja.Egreso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Correlativo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSoftDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Moneda_Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(9,2)");

                    b.Property<string>("Motivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroEgreso")
                        .HasColumnType("int");

                    b.Property<string>("Observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PrestamoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SocioInversionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PrestamoId");

                    b.HasIndex("SocioInversionId");

                    b.ToTable("Egreso");
                });

            modelBuilder.Entity("Cooperativa.App.Domain.Model.Caja.Ingreso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Correlativo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSoftDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Moneda_Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(9,2)");

                    b.Property<string>("Motivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroIngreso")
                        .HasColumnType("int");

                    b.Property<string>("Observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PrestamoDetalleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PrestamoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SocioInversionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PrestamoDetalleId");

                    b.HasIndex("PrestamoId");

                    b.HasIndex("SocioInversionId");

                    b.ToTable("Ingreso");
                });

            modelBuilder.Entity("Cooperativa.App.Domain.Model.Caja.Transaccion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("EgresoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<Guid?>("IngresoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsSoftDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Moneda_Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(9,2)");

                    b.Property<int>("NumeroTransaccion")
                        .HasColumnType("int");

                    b.Property<string>("Referencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoTransaccion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EgresoId");

                    b.HasIndex("IngresoId");

                    b.ToTable("Transaccion");
                });

            modelBuilder.Entity("Cooperativa.App.Domain.Model.Configuraciones.ConfiguracionPrestamo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSoftDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("PrimerMesInteresObligatorio")
                        .HasColumnType("bit");

                    b.Property<bool>("TomarSocioInversion")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("ConfiguracionPrestamo");
                });

            modelBuilder.Entity("Cooperativa.App.Domain.Model.People.Persona", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ciudad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoPersona")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("EstadoCivil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Genero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Identificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSoftDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LugarTrabajo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ocupacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtroContacto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pais")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RTN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TieneUsuario")
                        .HasColumnType("bit");

                    b.Property<string>("TipoIdentificacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Persona");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Persona");
                });

            modelBuilder.Entity("Cooperativa.App.Domain.Model.Prestamos.Prestamo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CantidadInicial")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CantidadMeses")
                        .HasColumnType("int");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClienteNombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoPrestamo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CuotaMensual")
                        .HasColumnType("decimal(9,3)");

                    b.Property<int>("CuotasPagadas")
                        .HasColumnType("int");

                    b.Property<int>("DebeMeses")
                        .HasColumnType("int");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("Estado_Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("EstimadoAPagarMes")
                        .HasColumnType("decimal(9,3)");

                    b.Property<DateTime>("FechaEntragado")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaEstimadoFinPrestamo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaUltimoPago")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Ganancia")
                        .HasColumnType("decimal(9,3)");

                    b.Property<string>("Garantia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("InteresPorcentaje")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsSoftDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MesesPagados")
                        .HasColumnType("int");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Moneda")
                        .HasColumnType("int");

                    b.Property<string>("Moneda_Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MontoPagado")
                        .HasColumnType("decimal(9,3)");

                    b.Property<decimal>("Mora")
                        .HasColumnType("decimal(9,3)");

                    b.Property<int>("NumeroPrestamo")
                        .HasColumnType("int");

                    b.Property<string>("Observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Responsable")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("RestaCapital")
                        .HasColumnType("decimal(9,3)");

                    b.Property<decimal>("TipoPrestamo")
                        .HasColumnType("decimal(9,3)");

                    b.Property<string>("TipoPrestamo_Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Prestamo");
                });

            modelBuilder.Entity("Cooperativa.App.Domain.Model.Prestamos.PrestamoDetalle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaProximoPago")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsSoftDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Moneda")
                        .HasColumnType("int");

                    b.Property<string>("Moneda_Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MontoCapital")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal>("MontoInteres")
                        .HasColumnType("decimal(9,2)");

                    b.Property<int>("NumeroCuota")
                        .HasColumnType("int");

                    b.Property<string>("Observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PrestamoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ProximoPago")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal>("RestaCapital")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal>("TotalAPagar")
                        .HasColumnType("decimal(9,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("PrestamoId");

                    b.ToTable("PrestamoDetalle");
                });

            modelBuilder.Entity("Cooperativa.App.Domain.Model.Socios.DetalleSocioInversion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CantidadPagadaDePrestamo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<decimal>("Ganancia")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("Habia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsSoftDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PorcentajeEnPrestamo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("PrestamoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Quedan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SePresto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("SocioInversionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PrestamoId");

                    b.HasIndex("SocioInversionId");

                    b.ToTable("DetalleSocioInversion");
                });

            modelBuilder.Entity("Cooperativa.App.Domain.Model.Socios.MovimientoDetalleSocio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,3)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DetalleSocioInversionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSoftDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DetalleSocioInversionId");

                    b.ToTable("MovimientoDetalleSocio");
                });

            modelBuilder.Entity("Cooperativa.App.Domain.Model.Socios.SocioInversion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CantidadPrestada")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CodigoInversion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("Estado_Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Ganancia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsSoftDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Moneda_Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Movimientos")
                        .HasColumnType("int");

                    b.Property<decimal>("NoPrestado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PorcetajePrestado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("SocioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SocioNombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SocioId");

                    b.ToTable("SocioInversion");
                });

            modelBuilder.Entity("Cooperativa.App.Domain.Model.People.Cliente", b =>
                {
                    b.HasBaseType("Cooperativa.App.Domain.Model.People.Persona");

                    b.Property<int?>("CantidadPrestamos")
                        .HasColumnType("int");

                    b.Property<bool>("ClienteBueno")
                        .HasColumnType("bit");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("Nota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PrestamoActivo")
                        .HasColumnType("bit");

                    b.Property<string>("RecomendadoPor")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Cliente");
                });

            modelBuilder.Entity("Cooperativa.App.Domain.Model.Socios.Socio", b =>
                {
                    b.HasBaseType("Cooperativa.App.Domain.Model.People.Persona");

                    b.Property<string>("Beneficiario_Identificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Beneficiario_Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CantidadInvensiones")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int")
                        .HasColumnName("Socio_Estado");

                    b.Property<DateTime>("FechaDeIngreso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaUltimaInversion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Parentesco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PorcentajeGanancia")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal?>("TotalMontoInvertido")
                        .HasColumnType("decimal(9,2)");

                    b.HasDiscriminator().HasValue("Socio");
                });

            modelBuilder.Entity("Cooperativa.App.Domain.Model.Caja.Caja", b =>
                {
                    b.HasOne("Cooperativa.App.Domain.Model.Caja.Egreso", "Egreso")
                        .WithMany()
                        .HasForeignKey("EgresoId");

                    b.HasOne("Cooperativa.App.Domain.Model.Caja.Ingreso", "Ingreso")
                        .WithMany()
                        .HasForeignKey("IngresoId");

                    b.Navigation("Egreso");

                    b.Navigation("Ingreso");
                });

            modelBuilder.Entity("Cooperativa.App.Domain.Model.Caja.Egreso", b =>
                {
                    b.HasOne("Cooperativa.App.Domain.Model.Prestamos.Prestamo", "Prestamo")
                        .WithMany()
                        .HasForeignKey("PrestamoId");

                    b.HasOne("Cooperativa.App.Domain.Model.Socios.SocioInversion", "SocioInversion")
                        .WithMany()
                        .HasForeignKey("SocioInversionId");

                    b.Navigation("Prestamo");

                    b.Navigation("SocioInversion");
                });

            modelBuilder.Entity("Cooperativa.App.Domain.Model.Caja.Ingreso", b =>
                {
                    b.HasOne("Cooperativa.App.Domain.Model.Prestamos.PrestamoDetalle", "PrestamoDetalle")
                        .WithMany()
                        .HasForeignKey("PrestamoDetalleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Cooperativa.App.Domain.Model.Prestamos.Prestamo", "Prestamo")
                        .WithMany()
                        .HasForeignKey("PrestamoId");

                    b.HasOne("Cooperativa.App.Domain.Model.Socios.SocioInversion", "SocioInversion")
                        .WithMany()
                        .HasForeignKey("SocioInversionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Prestamo");

                    b.Navigation("PrestamoDetalle");

                    b.Navigation("SocioInversion");
                });

            modelBuilder.Entity("Cooperativa.App.Domain.Model.Caja.Transaccion", b =>
                {
                    b.HasOne("Cooperativa.App.Domain.Model.Caja.Egreso", "Egreso")
                        .WithMany()
                        .HasForeignKey("EgresoId");

                    b.HasOne("Cooperativa.App.Domain.Model.Caja.Ingreso", "Ingreso")
                        .WithMany()
                        .HasForeignKey("IngresoId");

                    b.Navigation("Egreso");

                    b.Navigation("Ingreso");
                });

            modelBuilder.Entity("Cooperativa.App.Domain.Model.Prestamos.Prestamo", b =>
                {
                    b.HasOne("Cooperativa.App.Domain.Model.People.Cliente", "Cliente")
                        .WithMany("Prestamos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Cooperativa.App.Domain.Model.Prestamos.PrestamoDetalle", b =>
                {
                    b.HasOne("Cooperativa.App.Domain.Model.People.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cooperativa.App.Domain.Model.Prestamos.Prestamo", "Prestamo")
                        .WithMany("PrestamoDetalles")
                        .HasForeignKey("PrestamoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Prestamo");
                });

            modelBuilder.Entity("Cooperativa.App.Domain.Model.Socios.DetalleSocioInversion", b =>
                {
                    b.HasOne("Cooperativa.App.Domain.Model.Prestamos.Prestamo", "Prestamo")
                        .WithMany()
                        .HasForeignKey("PrestamoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cooperativa.App.Domain.Model.Socios.SocioInversion", "SocioInversion")
                        .WithMany("DetallesSocioInversion")
                        .HasForeignKey("SocioInversionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Prestamo");

                    b.Navigation("SocioInversion");
                });

            modelBuilder.Entity("Cooperativa.App.Domain.Model.Socios.MovimientoDetalleSocio", b =>
                {
                    b.HasOne("Cooperativa.App.Domain.Model.Socios.DetalleSocioInversion", "DetalleSocioInversion")
                        .WithMany("MovimientosDetalleSocio")
                        .HasForeignKey("DetalleSocioInversionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DetalleSocioInversion");
                });

            modelBuilder.Entity("Cooperativa.App.Domain.Model.Socios.SocioInversion", b =>
                {
                    b.HasOne("Cooperativa.App.Domain.Model.Socios.Socio", "Socio")
                        .WithMany("SocioInversiones")
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("Cooperativa.App.Domain.Model.Prestamos.Prestamo", b =>
                {
                    b.Navigation("PrestamoDetalles");
                });

            modelBuilder.Entity("Cooperativa.App.Domain.Model.Socios.DetalleSocioInversion", b =>
                {
                    b.Navigation("MovimientosDetalleSocio");
                });

            modelBuilder.Entity("Cooperativa.App.Domain.Model.Socios.SocioInversion", b =>
                {
                    b.Navigation("DetallesSocioInversion");
                });

            modelBuilder.Entity("Cooperativa.App.Domain.Model.People.Cliente", b =>
                {
                    b.Navigation("Prestamos");
                });

            modelBuilder.Entity("Cooperativa.App.Domain.Model.Socios.Socio", b =>
                {
                    b.Navigation("SocioInversiones");
                });
#pragma warning restore 612, 618
        }
    }
}
