// <auto-generated />
using System;
using Cooperativa.App.Domain.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Cooperativa.App.Migrations
{
    [DbContext(typeof(CooperativaDbContext))]
    [Migration("20251102033615_updacaj")]
    partial class updacaj
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Cooperativa.App.Domain.Model.Caja.Caja", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("EgresoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<Guid?>("IngresoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsSoftDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Moneda_Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Referencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ResponsableId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("SaldoActual")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal>("SaldoAnterior")
                        .HasColumnType("decimal(9,2)");

                    b.HasKey("Id");

                    b.HasIndex("EgresoId");

                    b.HasIndex("IngresoId");

                    b.ToTable("Caja");
                });

            modelBuilder.Entity("Cooperativa.App.Domain.Model.Caja.Egreso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Correlativo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSoftDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Moneda_Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(9,2)");

                    b.Property<string>("Motivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroEgreso")
                        .HasColumnType("int");

                    b.Property<string>("Observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PrestamoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RetiroId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RetiroId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SocioInversionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PrestamoId");

                    b.HasIndex("RetiroId1");

                    b.HasIndex("SocioInversionId");

                    b.ToTable("Egreso");
                });

            modelBuilder.Entity("Cooperativa.App.Domain.Model.Caja.HistorialCambioMoneda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ColonCostaRica")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal>("CordobaNicaragua")
                        .HasColumnType("decimal(9,2)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Dolar")
                        .HasColumnType("decimal(9,2)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<decimal>("Euro")
                        .HasColumnType("decimal(9,2)");

                    b.Property<bool>("IsSoftDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Lempira")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal>("MXN")
                        .HasColumnType("decimal(9,2)");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MonedaBase")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Quetzal")
                        .HasColumnType("decimal(9,2)");

                    b.HasKey("Id");

                    b.ToTable("HistorialCambioMoneda");
                });

            modelBuilder.Entity("Cooperativa.App.Domain.Model.Caja.Ingreso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Correlativo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSoftDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Moneda_Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(9,2)");

                    b.Property<string>("Motivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroIngreso")
                        .HasColumnType("int");

                    b.Property<string>("Observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PrestamoDetalleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PrestamoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SocioInversionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PrestamoDetalleId");

                    b.HasIndex("PrestamoId");

                    b.HasIndex("SocioInversionId");

                    b.ToTable("Ingreso");
                });

            modelBuilder.Entity("Cooperativa.App.Domain.Model.Caja.Retiro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CajaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CantidadEnDolar")
                        .HasColumnType("decimal(9,3)");

                    b.Property<decimal>("CantidadEnEuro")
                        .HasColumnType("decimal(9,3)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CuentaBancariaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EgresoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("Estado_Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("HistorialCambioMonedaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsSoftDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Moneda_Descripcion")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(9,3)");

                    b.Property<string>("Motivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroRetiro")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PrestamoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ResponsableAtendioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SolicitanteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TipoRetiro")
                        .HasColumnType("int");

                    b.Property<string>("TipoRetiro_Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CajaId");

                    b.HasIndex("CuentaBancariaId");

                    b.HasIndex("EgresoId");

                    b.HasIndex("HistorialCambioMonedaId");

                    b.HasIndex("PrestamoId");

                    b.HasIndex("ResponsableAtendioId");

                    b.HasIndex("SolicitanteId");

                    b.ToTable("Retiro");
                });

            modelBuilder.Entity("Cooperativa.App.Domain.Model.Caja.SocioInversionRetiro", b =>
                {
                    b.Property<Guid>("SocioInversionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RetiroId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(9,3)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsSoftDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("SocioInversionId", "RetiroId");

                    b.HasIndex("RetiroId");

                    b.ToTable("SocioInversionRetiro");
                });

            modelBuilder.Entity("Cooperativa.App.Domain.Model.Caja.Transaccion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CajaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("EgresoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<Guid?>("IngresoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsSoftDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Moneda_Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(9,2)");

                    b.Property<int>("NumeroTransaccion")
                        .HasColumnType("int");

                    b.Property<string>("Referencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoTransaccion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CajaId");

                    b.HasIndex("EgresoId");

                    b.HasIndex("IngresoId");

                    b.ToTable("Transaccion");
                });

            modelBuilder.Entity("Cooperativa.App.Domain.Model.Configuraciones.ConfiguracionPrestamo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CantidadPrestamosPorCliente")
                        .HasColumnType("int");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DiasDeGracias")
                        .HasColumnType("int");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("HistoricoCambios")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("InteresAnual")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal>("InteresPIM")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal>("InteresPorMora")
                        .HasColumnType("decimal(9,2)");

                    b.Property<bool>("IsSoftDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MonedaPorDefecto")
                        .HasColumnType("int");

                    b.Property<string>("Moneda_Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MontoMaximo")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal>("MontoMinimo")
                        .HasColumnType("decimal(9,2)");

                    b.Property<string>("Observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PlazoMesesMaximo")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal>("PlazoMesesMinimo")
                        .HasColumnType("decimal(9,2)");

                    b.Property<bool>("PrimerMesInteresObligatorio")
                        .HasColumnType("bit");

                    b.Property<bool>("TomarSocioInversion")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("ConfiguracionPrestamo");
                });

            modelBuilder.Entity("Cooperativa.App.Domain.Model.EntidadesUtiles.Secuencial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodigoBase")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("Entidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSoftDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UltimoSecuencial")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Secuencial");
                });

            modelBuilder.Entity("Cooperativa.App.Domain.Model.EntidadesUtiles.TasasCambioDivisa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Diferencia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Fuente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSoftDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MonedaBase")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MonedaDestino")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Tasa")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TasaAnterior")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("TasasCambioDivisa");
                });

            modelBuilder.Entity("Cooperativa.App.Domain.Model.People.CuentaBancaria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CajaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CantidadMovimientos")
                        .HasColumnType("int");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaUltimoMovimiento")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("InstitucionBancariaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsSoftDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumeroCuenta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumeroTarjeta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PersonaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("SaldoAnterior")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal>("SaldoTotalTransferido")
                        .HasColumnType("decimal(9,2)");

                    b.Property<int>("TipoCuenta")
                        .HasColumnType("int");

                    b.Property<string>("TipoCuenta_Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("UltimoMovimiento")
                        .HasColumnType("decimal(9,2)");

                    b.HasKey("Id");

                    b.HasIndex("CajaId");

                    b.HasIndex("InstitucionBancariaId");

                    b.HasIndex("PersonaId");

                    b.ToTable("CuentaBancaria");
                });

            modelBuilder.Entity("Cooperativa.App.Domain.Model.People.InstitucionBancaria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSoftDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pais")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SitioWeb")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoInstitucion")
                        .HasColumnType("int");

                    b.Property<string>("TipoInstitucion_Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("InstitucionBancaria");
                });

            modelBuilder.Entity("Cooperativa.App.Domain.Model.People.Persona", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ciudad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoPersona")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("EstadoCivil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Genero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Identificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSoftDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LugarTrabajo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ocupacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtroContacto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pais")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RTN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TieneUsuario")
                        .HasColumnType("bit");

                    b.Property<string>("TipoIdentificacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Persona");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Persona");
                });

            modelBuilder.Entity("Cooperativa.App.Domain.Model.Prestamos.Prestamo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CantidadEnDolar")
                        .HasColumnType("decimal(9,3)");

                    b.Property<decimal>("CantidadEnEuro")
                        .HasColumnType("decimal(9,3)");

                    b.Property<decimal>("CantidadInicial")
                        .HasColumnType("decimal(9,3)");

                    b.Property<int>("CantidadMeses")
                        .HasColumnType("int");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClienteNombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoPrestamo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CuentaBancariaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CuotaMensual")
                        .HasColumnType("decimal(9,3)");

                    b.Property<int>("CuotasPagadas")
                        .HasColumnType("int");

                    b.Property<int>("DebeMeses")
                        .HasColumnType("int");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("Estado_Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("EstimadoAPagarMes")
                        .HasColumnType("decimal(9,3)");

                    b.Property<DateTime>("FechaEntragado")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaEstimadoFinPrestamo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaUltimoPago")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Ganancia")
                        .HasColumnType("decimal(9,3)");

                    b.Property<string>("Garantia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("HistorialCambioMonedaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("InteresPorcentaje")
                        .HasColumnType("decimal(9,2)");

                    b.Property<bool>("IsSoftDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LinkDocumento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MesesPagados")
                        .HasColumnType("int");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Moneda")
                        .HasColumnType("int");

                    b.Property<string>("Moneda_Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MontoPagado")
                        .HasColumnType("decimal(9,3)");

                    b.Property<decimal>("Mora")
                        .HasColumnType("decimal(9,3)");

                    b.Property<int>("NumeroPrestamo")
                        .HasColumnType("int");

                    b.Property<string>("Observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferenciaBancaria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("RequiereDocumento")
                        .HasColumnType("bit");

                    b.Property<Guid>("Responsable")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("RestaCapital")
                        .HasColumnType("decimal(9,3)");

                    b.Property<int>("TipoPrestamo")
                        .HasColumnType("int");

                    b.Property<string>("TipoPrestamo_Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("CuentaBancariaId");

                    b.HasIndex("HistorialCambioMonedaId");

                    b.ToTable("Prestamo");
                });

            modelBuilder.Entity("Cooperativa.App.Domain.Model.Prestamos.PrestamoDetalle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CuentaBancariaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DiasDeGraciasAplicados")
                        .HasColumnType("int");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaProximoPago")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsSoftDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Moneda")
                        .HasColumnType("int");

                    b.Property<string>("Moneda_Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MontoCapital")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal>("MontoInteres")
                        .HasColumnType("decimal(9,2)");

                    b.Property<int>("NumeroCuota")
                        .HasColumnType("int");

                    b.Property<string>("Observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PrestamoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ProximoPago")
                        .HasColumnType("decimal(9,2)");

                    b.Property<string>("ReferenciaBancaria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("RestaCapital")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal>("TotalAPagar")
                        .HasColumnType("decimal(9,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("CuentaBancariaId");

                    b.HasIndex("PrestamoId");

                    b.ToTable("PrestamoDetalle");
                });

            modelBuilder.Entity("Cooperativa.App.Domain.Model.Socios.DetalleSocioInversion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CantidadPagadaDePrestamo")
                        .HasColumnType("decimal(9,3)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<decimal>("Ganancia")
                        .HasColumnType("decimal(9,3)");

                    b.Property<Guid?>("GananciaDetalleSocioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GananciaDetalleSocioId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Habia")
                        .HasColumnType("decimal(9,3)");

                    b.Property<bool>("IsSoftDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PorcentajeEnPrestamo")
                        .HasColumnType("decimal(9,3)");

                    b.Property<Guid>("PrestamoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Quedan")
                        .HasColumnType("decimal(9,3)");

                    b.Property<decimal>("SePresto")
                        .HasColumnType("decimal(9,3)");

                    b.Property<Guid>("SocioInversionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GananciaDetalleSocioId1");

                    b.HasIndex("PrestamoId");

                    b.HasIndex("SocioInversionId");

                    b.ToTable("DetalleSocioInversion");
                });

            modelBuilder.Entity("Cooperativa.App.Domain.Model.Socios.GananciaDetalleSocio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CantidadDisponibleARetirar")
                        .HasColumnType("decimal(9,3)");

                    b.Property<decimal>("CantidadRetirada")
                        .HasColumnType("decimal(9,3)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DeCantidad")
                        .HasColumnType("decimal(9,3)");

                    b.Property<Guid>("DetalleSocioInversionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<decimal>("Ganancia")
                        .HasColumnType("decimal(9,3)");

                    b.Property<Guid?>("GananciaDetalleSocioAnteriorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsSoftDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Retirado")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DetalleSocioInversionId");

                    b.HasIndex("GananciaDetalleSocioAnteriorId");

                    b.ToTable("GananciaDetalleSocio");
                });

            modelBuilder.Entity("Cooperativa.App.Domain.Model.Socios.MovimientoDetalleSocio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(9,3)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DetalleSocioInversionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSoftDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DetalleSocioInversionId");

                    b.ToTable("MovimientoDetalleSocio");
                });

            modelBuilder.Entity("Cooperativa.App.Domain.Model.Socios.SocioInversion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(9,3)");

                    b.Property<decimal>("CantidadActiva")
                        .HasColumnType("decimal(9,3)");

                    b.Property<decimal>("CantidadDisponibleRetirar")
                        .HasColumnType("decimal(9,3)");

                    b.Property<decimal>("CantidadEnDolar")
                        .HasColumnType("decimal(9,3)");

                    b.Property<decimal>("CantidadEnEuro")
                        .HasColumnType("decimal(9,3)");

                    b.Property<decimal>("CantidadPrestada")
                        .HasColumnType("decimal(9,3)");

                    b.Property<string>("CodigoInversion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CuentaBancariaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("Estado_Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Ganancia")
                        .HasColumnType("decimal(9,3)");

                    b.Property<decimal>("GananciaDisponible")
                        .HasColumnType("decimal(9,3)");

                    b.Property<Guid?>("HistorialCambioMonedaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsSoftDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Moneda_Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Movimientos")
                        .HasColumnType("int");

                    b.Property<decimal>("NoPrestado")
                        .HasColumnType("decimal(9,3)");

                    b.Property<decimal>("PorcetajePrestado")
                        .HasColumnType("decimal(9,3)");

                    b.Property<decimal>("Retirado")
                        .HasColumnType("decimal(9,3)");

                    b.Property<Guid>("SocioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SocioNombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CuentaBancariaId");

                    b.HasIndex("HistorialCambioMonedaId");

                    b.HasIndex("SocioId");

                    b.ToTable("SocioInversion");
                });

            modelBuilder.Entity("Cooperativa.App.Domain.Model.People.Cliente", b =>
                {
                    b.HasBaseType("Cooperativa.App.Domain.Model.People.Persona");

                    b.Property<int?>("CantidadPrestamos")
                        .HasColumnType("int");

                    b.Property<bool>("ClienteBueno")
                        .HasColumnType("bit");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("Nota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PrestamoActivo")
                        .HasColumnType("bit");

                    b.Property<string>("RecomendadoPor")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Cliente");
                });

            modelBuilder.Entity("Cooperativa.App.Domain.Model.Socios.Socio", b =>
                {
                    b.HasBaseType("Cooperativa.App.Domain.Model.People.Persona");

                    b.Property<string>("Beneficiario_Identificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Beneficiario_Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CantidadInvensiones")
                        .HasColumnType("int");

                    b.Property<int>("CantidadRetiros")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int")
                        .HasColumnName("Socio_Estado");

                    b.Property<DateTime>("FechaDeIngreso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaUltimaInversion")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("GananciaTotal")
                        .HasColumnType("decimal(9,3)");

                    b.Property<string>("Parentesco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PorcentajeGanancia")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal>("SaldoDisponibleARetirar")
                        .HasColumnType("decimal(9,3)");

                    b.Property<decimal?>("TotalMontoInvertido")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal>("TotalRetirado")
                        .HasColumnType("decimal(9,3)");

                    b.HasDiscriminator().HasValue("Socio");
                });

            modelBuilder.Entity("Cooperativa.App.Domain.Model.Caja.Caja", b =>
                {
                    b.HasOne("Cooperativa.App.Domain.Model.Caja.Egreso", "Egreso")
                        .WithMany()
                        .HasForeignKey("EgresoId");

                    b.HasOne("Cooperativa.App.Domain.Model.Caja.Ingreso", "Ingreso")
                        .WithMany()
                        .HasForeignKey("IngresoId");

                    b.Navigation("Egreso");

                    b.Navigation("Ingreso");
                });

            modelBuilder.Entity("Cooperativa.App.Domain.Model.Caja.Egreso", b =>
                {
                    b.HasOne("Cooperativa.App.Domain.Model.Prestamos.Prestamo", "Prestamo")
                        .WithMany()
                        .HasForeignKey("PrestamoId");

                    b.HasOne("Cooperativa.App.Domain.Model.Caja.Retiro", "Retiro")
                        .WithMany()
                        .HasForeignKey("RetiroId1");

                    b.HasOne("Cooperativa.App.Domain.Model.Socios.SocioInversion", "SocioInversion")
                        .WithMany()
                        .HasForeignKey("SocioInversionId");

                    b.Navigation("Prestamo");

                    b.Navigation("Retiro");

                    b.Navigation("SocioInversion");
                });

            modelBuilder.Entity("Cooperativa.App.Domain.Model.Caja.Ingreso", b =>
                {
                    b.HasOne("Cooperativa.App.Domain.Model.Prestamos.PrestamoDetalle", "PrestamoDetalle")
                        .WithMany()
                        .HasForeignKey("PrestamoDetalleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Cooperativa.App.Domain.Model.Prestamos.Prestamo", "Prestamo")
                        .WithMany()
                        .HasForeignKey("PrestamoId");

                    b.HasOne("Cooperativa.App.Domain.Model.Socios.SocioInversion", "SocioInversion")
                        .WithMany()
                        .HasForeignKey("SocioInversionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Prestamo");

                    b.Navigation("PrestamoDetalle");

                    b.Navigation("SocioInversion");
                });

            modelBuilder.Entity("Cooperativa.App.Domain.Model.Caja.Retiro", b =>
                {
                    b.HasOne("Cooperativa.App.Domain.Model.Caja.Caja", "Caja")
                        .WithMany()
                        .HasForeignKey("CajaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cooperativa.App.Domain.Model.People.CuentaBancaria", "CuentaBancaria")
                        .WithMany()
                        .HasForeignKey("CuentaBancariaId");

                    b.HasOne("Cooperativa.App.Domain.Model.Caja.Egreso", "Egreso")
                        .WithMany()
                        .HasForeignKey("EgresoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Cooperativa.App.Domain.Model.Caja.HistorialCambioMoneda", "HistorialCambioMoneda")
                        .WithMany()
                        .HasForeignKey("HistorialCambioMonedaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Cooperativa.App.Domain.Model.Prestamos.Prestamo", "Prestamo")
                        .WithMany()
                        .HasForeignKey("PrestamoId");

                    b.HasOne("Cooperativa.App.Domain.Model.Socios.Socio", "ResponsableAtendio")
                        .WithMany()
                        .HasForeignKey("ResponsableAtendioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Cooperativa.App.Domain.Model.Socios.Socio", "Solicitante")
                        .WithMany()
                        .HasForeignKey("SolicitanteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Caja");

                    b.Navigation("CuentaBancaria");

                    b.Navigation("Egreso");

                    b.Navigation("HistorialCambioMoneda");

                    b.Navigation("Prestamo");

                    b.Navigation("ResponsableAtendio");

                    b.Navigation("Solicitante");
                });

            modelBuilder.Entity("Cooperativa.App.Domain.Model.Caja.SocioInversionRetiro", b =>
                {
                    b.HasOne("Cooperativa.App.Domain.Model.Caja.Retiro", "Retiro")
                        .WithMany("SocioInversionRetiros")
                        .HasForeignKey("RetiroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cooperativa.App.Domain.Model.Socios.SocioInversion", "SocioInversion")
                        .WithMany("SocioInversionRetiros")
                        .HasForeignKey("SocioInversionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Retiro");

                    b.Navigation("SocioInversion");
                });

            modelBuilder.Entity("Cooperativa.App.Domain.Model.Caja.Transaccion", b =>
                {
                    b.HasOne("Cooperativa.App.Domain.Model.Caja.Caja", "Caja")
                        .WithMany("Transacciones")
                        .HasForeignKey("CajaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Cooperativa.App.Domain.Model.Caja.Egreso", "Egreso")
                        .WithMany()
                        .HasForeignKey("EgresoId");

                    b.HasOne("Cooperativa.App.Domain.Model.Caja.Ingreso", "Ingreso")
                        .WithMany()
                        .HasForeignKey("IngresoId");

                    b.Navigation("Caja");

                    b.Navigation("Egreso");

                    b.Navigation("Ingreso");
                });

            modelBuilder.Entity("Cooperativa.App.Domain.Model.People.CuentaBancaria", b =>
                {
                    b.HasOne("Cooperativa.App.Domain.Model.Caja.Caja", "Caja")
                        .WithMany("CuentaBancarias")
                        .HasForeignKey("CajaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Cooperativa.App.Domain.Model.People.InstitucionBancaria", "InstitucionBancaria")
                        .WithMany()
                        .HasForeignKey("InstitucionBancariaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Cooperativa.App.Domain.Model.People.Persona", "Persona")
                        .WithMany("CuentaBancarias")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Caja");

                    b.Navigation("InstitucionBancaria");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("Cooperativa.App.Domain.Model.Prestamos.Prestamo", b =>
                {
                    b.HasOne("Cooperativa.App.Domain.Model.People.Cliente", "Cliente")
                        .WithMany("Prestamos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cooperativa.App.Domain.Model.People.CuentaBancaria", "CuentaBancaria")
                        .WithMany()
                        .HasForeignKey("CuentaBancariaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Cooperativa.App.Domain.Model.Caja.HistorialCambioMoneda", "HistorialCambioMoneda")
                        .WithMany()
                        .HasForeignKey("HistorialCambioMonedaId");

                    b.Navigation("Cliente");

                    b.Navigation("CuentaBancaria");

                    b.Navigation("HistorialCambioMoneda");
                });

            modelBuilder.Entity("Cooperativa.App.Domain.Model.Prestamos.PrestamoDetalle", b =>
                {
                    b.HasOne("Cooperativa.App.Domain.Model.People.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cooperativa.App.Domain.Model.People.CuentaBancaria", "CuentaBancaria")
                        .WithMany()
                        .HasForeignKey("CuentaBancariaId");

                    b.HasOne("Cooperativa.App.Domain.Model.Prestamos.Prestamo", "Prestamo")
                        .WithMany("PrestamoDetalles")
                        .HasForeignKey("PrestamoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("CuentaBancaria");

                    b.Navigation("Prestamo");
                });

            modelBuilder.Entity("Cooperativa.App.Domain.Model.Socios.DetalleSocioInversion", b =>
                {
                    b.HasOne("Cooperativa.App.Domain.Model.Socios.GananciaDetalleSocio", "GananciaDetalleSocio")
                        .WithMany()
                        .HasForeignKey("GananciaDetalleSocioId1");

                    b.HasOne("Cooperativa.App.Domain.Model.Prestamos.Prestamo", "Prestamo")
                        .WithMany()
                        .HasForeignKey("PrestamoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cooperativa.App.Domain.Model.Socios.SocioInversion", "SocioInversion")
                        .WithMany("DetallesSocioInversion")
                        .HasForeignKey("SocioInversionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GananciaDetalleSocio");

                    b.Navigation("Prestamo");

                    b.Navigation("SocioInversion");
                });

            modelBuilder.Entity("Cooperativa.App.Domain.Model.Socios.GananciaDetalleSocio", b =>
                {
                    b.HasOne("Cooperativa.App.Domain.Model.Socios.DetalleSocioInversion", "DetalleSocioInversion")
                        .WithMany()
                        .HasForeignKey("DetalleSocioInversionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cooperativa.App.Domain.Model.Socios.GananciaDetalleSocio", "GananciaDetalleSocioAnterior")
                        .WithMany()
                        .HasForeignKey("GananciaDetalleSocioAnteriorId");

                    b.Navigation("DetalleSocioInversion");

                    b.Navigation("GananciaDetalleSocioAnterior");
                });

            modelBuilder.Entity("Cooperativa.App.Domain.Model.Socios.MovimientoDetalleSocio", b =>
                {
                    b.HasOne("Cooperativa.App.Domain.Model.Socios.DetalleSocioInversion", "DetalleSocioInversion")
                        .WithMany("MovimientosDetalleSocio")
                        .HasForeignKey("DetalleSocioInversionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DetalleSocioInversion");
                });

            modelBuilder.Entity("Cooperativa.App.Domain.Model.Socios.SocioInversion", b =>
                {
                    b.HasOne("Cooperativa.App.Domain.Model.People.CuentaBancaria", "CuentaBancaria")
                        .WithMany()
                        .HasForeignKey("CuentaBancariaId");

                    b.HasOne("Cooperativa.App.Domain.Model.Caja.HistorialCambioMoneda", "HistorialCambioMoneda")
                        .WithMany()
                        .HasForeignKey("HistorialCambioMonedaId");

                    b.HasOne("Cooperativa.App.Domain.Model.Socios.Socio", "Socio")
                        .WithMany("SocioInversiones")
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CuentaBancaria");

                    b.Navigation("HistorialCambioMoneda");

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("Cooperativa.App.Domain.Model.Caja.Caja", b =>
                {
                    b.Navigation("CuentaBancarias");

                    b.Navigation("Transacciones");
                });

            modelBuilder.Entity("Cooperativa.App.Domain.Model.Caja.Retiro", b =>
                {
                    b.Navigation("SocioInversionRetiros");
                });

            modelBuilder.Entity("Cooperativa.App.Domain.Model.People.Persona", b =>
                {
                    b.Navigation("CuentaBancarias");
                });

            modelBuilder.Entity("Cooperativa.App.Domain.Model.Prestamos.Prestamo", b =>
                {
                    b.Navigation("PrestamoDetalles");
                });

            modelBuilder.Entity("Cooperativa.App.Domain.Model.Socios.DetalleSocioInversion", b =>
                {
                    b.Navigation("MovimientosDetalleSocio");
                });

            modelBuilder.Entity("Cooperativa.App.Domain.Model.Socios.SocioInversion", b =>
                {
                    b.Navigation("DetallesSocioInversion");

                    b.Navigation("SocioInversionRetiros");
                });

            modelBuilder.Entity("Cooperativa.App.Domain.Model.People.Cliente", b =>
                {
                    b.Navigation("Prestamos");
                });

            modelBuilder.Entity("Cooperativa.App.Domain.Model.Socios.Socio", b =>
                {
                    b.Navigation("SocioInversiones");
                });
#pragma warning restore 612, 618
        }
    }
}
